### ISSUE TITLE
Apple Touch Icons

### ISSUE THREAD

**Issue by rebeccafae** [womenrising/womenrising#103]
Add apple touch icons so we will stop receiving `No route matches` errors

![uploads/2b8c28df-ba6f-4984-b553-fa7d3673adf9/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2b8c28df-ba6f-4984-b553-fa7d3673adf9%2Fimage.png)

**Comment by timkleier** [comment]
@rebeccafae, I'm ready to submit a pull request, but I wanted to ask a couple things first. I can't consistently reproduce the error (possibly due to browser caching) and I'm assuming we don't need test coverage on this as we don't have tests for other images. 1) could you provide steps to reproduce and 2), do we need test coverage on this?

**Comment by rebeccafae** [comment]
Thanks @timkleier 

No we do not need a test for this. To reproduce you can either go to the url with the icon or on an iPhone choose "Add to Home Screen", and see if a Rollbar error occur. But you will not have access to the rollbar, and it will not appear on Rollbar until we have it merged and on staging (http://womenrising-staging.herokuapp.com). So unfortunately there is not a good way to reproduce the error that you would see . But you can probably watch the logs locally to see what would get sent to Rollbar instead.

Let me know if you need anything else :-)
