### ISSUE TITLE
Consider pairing up fewer people for peer meetup

### ISSUE THREAD

**Issue by SpaceOtterInSpace** [womenrising/womenrising#109]
I have enjoyed being paired up on this site but have found it particularly difficult to organize a casual meetup of four working women. Can you consider pairing up only two people? Is there any measure of success for other people meeting up?

Also, when it's four people, everyone is hesitant to meet up unless everyone is available.

**Comment by rebeccafae** [comment]
@SpaceOtterInSpace thanks for your feedback.

The groups currently range from 2-4 people, depending on how many people have signed up for that area. (3 is the ideal size that we aim for)

We have a [github issue](https://github.com/womenrising/womenrising/issues/55) to get feedback about if the groups are meeting, but that story has not yet been started.

If you have any more feedback @KateCatlin and I would love to hear it. I am going to close this issue because I believe all the concerns are already addressed by other github issues.
